# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='spacing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
